affiliate_address: "0x2905d7e4d048d29954f81b02171dd313f457a4a4"
claiming_address: "0x2905d7e4d048d29954f81b02171dd313f457a4a4"
chains:
  - name: base
    rpc_url: https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}
    start_block: 32900000
    router_addresses:
      - "0xF5042e6ffaC5a625D4E7848e0b01373D8eB9e222"
      - "0xeeeeee9eC4769A09a76A83C7bC42b185872860eE"
  - name: arbitrum
    rpc_url: https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}
    start_block: 358000000
    router_addresses:
      - "0xF5042e6ffaC5a625D4E7848e0b01373D8eB9e222"
  - name: optimism
    rpc_url: https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}
    start_block: 118300000
    router_addresses:
      - "0xF5042e6ffaC5a625D4E7848e0b01373D8eB9e222"
      - "0xeeeeee9eC4769A09a76A83C7bC42b185872860eE"
  - name: avalanche
    rpc_url: https://avalanche-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}
    start_block: 41500000
    router_addresses:
      - "0xF5042e6ffaC5a625D4E7848e0b01373D8eB9e222"
  - name: polygon
    rpc_url: https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}
    start_block: 59800000
    router_addresses:
      - "0xF5042e6ffaC5a625D4E7848e0b01373D8eB9e222"
db:
  path: databases/affiliate.db 