# ShapeShift Affiliate Tracker Configuration
# Centralized configuration for all listeners and components

# API Keys and RPC Endpoints
api:
  alchemy_api_key: "${ALCHEMY_API_KEY}"
  infura_api_key: "${INFURA_API_KEY}"
  coinmarketcap_api_key: "${COINMARKETCAP_API_KEY}"

# ShapeShift Affiliate Addresses (all known variations)
shapeshift_affiliates:
  # Primary ShapeShift addresses
  primary: "0x35339070f178dC4119732982C23F5a8d88D3f8a3"  # Main Relay affiliate
  relay: "0x35339070f178dC4119732982C23F5a8d88D3f8a3"    # Relay affiliate
  portals: "0x35339070f178dC4119732982C23F5a8d88D3f8a3"   # Portals affiliate
  thorchain: "0x35339070f178dC4119732982C23F5a8d88D3f8a3" # ThorChain affiliate
  cowswap: "0x35339070f178dC4119732982C23F5a8d88D3f8a3"   # CoW Swap affiliate
  
  # Alternative/legacy addresses found in data
  legacy_relay: "0x2905d7e4d048d29954f81b02171dd313f457a4a4"  # Found in existing data
  legacy_portals: "0x0840bba848e991cdcfbf2b71b8e1cb94fb72d6343ad4bb182f7ee1c48612221d"  # From Portals data
  
  # Protocol-specific addresses
  thorchain_address: "thor122h9hlrugzdny9ct95z6g7afvpzu34s73uklju"  # THORChain affiliate address
  thorchain_name: "ss"  # THORChain affiliate name abbreviation
  
  # Common variations
  variations:
    - "0x35339070f178dC4119732982C23F5a8d88D3f8a3"  # Current primary
    - "0x2905d7e4d048d29954f81b02171dd313f457a4a4"  # Legacy
    - "0x0840bba848e991cdcfbf2b71b8e1cb94fb72d6343ad4bb182f7ee1c48612221d"  # Portals
    - "shapeshift"  # Text variations
    - "ss"  # Abbreviation
    - "ShapeShift"  # Capitalized
    - "SHAPESHIFT"  # All caps

# Chain Configurations
chains:
  ethereum:
    name: "Ethereum Mainnet"
    chain_id: 1
    rpc_url: "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
    start_block: 19000000
    chunk_size: 100
    delay: 0.5
    
  polygon:
    name: "Polygon PoS"
    chain_id: 137
    rpc_url: "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
    start_block: 50000000
    chunk_size: 100
    delay: 0.5
    
  arbitrum:
    name: "Arbitrum One"
    chain_id: 42161
    rpc_url: "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
    start_block: 100000000
    chunk_size: 100
    delay: 0.5
    
  optimism:
    name: "Optimism"
    chain_id: 10
    rpc_url: "https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
    start_block: 50000000
    chunk_size: 100
    delay: 0.5
    
  base:
    name: "Base"
    chain_id: 8453
    rpc_url: "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
    start_block: 32900000
    chunk_size: 100
    delay: 0.5
    
  avalanche:
    name: "Avalanche"
    chain_id: 43114
    rpc_url: "https://api.avax.network/ext/bc/C/rpc"
    start_block: 30000000
    chunk_size: 100
    delay: 0.5

# Protocol-Specific Contract Addresses
contracts:
  relay:
    # Relay router addresses across chains
    ethereum: "0x542f021da7834c7f81531b48961d3f467f54b0f08"
    polygon: "0x542f021da7834c7f81531b48961d3f467f54b0f08"
    arbitrum: "0x542f021da7834c7f81531b48961d3f467f54b0f08"
    optimism: "0x542f021da7834c7f81531b48961d3f467f54b0f08"
    base: "0xF5042e6ffaC5a625D4E7848e0b01373D8eB9e222"
    avalanche: "0x542f021da7834c7f81531b48961d3f467f54b0f08"
    
    # Alternative router addresses
    base_alternative: "0xeeeeee9eC4769A09a76A83C7bC42b185872860eE"  # ETH router
    
    # Event signatures
    affiliate_fee_event: "0x4a25d94a55df505cf9da1f1649d0381e2613c3c83c6a0a3df055ae0e82f6e4d7"
    transfer_event: "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"
    
  portals:
    # Portals contract addresses
    ethereum: "0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23"
    polygon: "0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23"
    arbitrum: "0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23"
    optimism: "0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23"
    base: "0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23"
    avalanche: "0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23"
    
    # Event signatures
    affiliate_fee_event: "0x4a25d94a55df505cf9da1f1649d0381e2613c3c83c6a0a3df055ae0e82f6e4d7"
    
  thorchain:
    # ThorChain API endpoints
    midgard_api: "https://midgard.ninerealms.com/v2"
    thornode_api: "https://thornode.ninerealms.com"
    
    # ThorChain addresses (if any)
    affiliate_address: "thor122h9hlrugzdny9ct95z6g7afvpzu34s73uklju"
    affiliate_name: "ss"
    
  cowswap:
    # CoW Swap contract addresses
    ethereum: "0x9008d19f58aabd9ed0d60971565aa8510560ab41"
    polygon: "0x9008d19f58aabd9ed0d60971565aa8510560ab41"
    arbitrum: "0x9008d19f58aabd9ed0d60971565aa8510560ab41"
    optimism: "0x9008d19f58aabd9ed0d60971565aa8510560ab41"
    base: "0x9008d19f58aabd9ed0d60971565aa8510560ab41"
    avalanche: "0x9008d19f58aabd9ed0d60971565aa8510560ab41"
    
    # Event signatures
    order_event: "0x0bcc4c97732e47d9946f229edb95f5e6320829021d42f1eec4c37c14845c8a8e"

# Data Storage Configuration
storage:
  csv_directory: "csv_data"
  database_directory: "databases"
  backup_directory: "backups"
  
  # File naming conventions
  file_patterns:
    portals: "portals_transactions.csv"
    relay: "relay_transactions.csv"
    thorchain: "thorchain_transactions.csv"
    cowswap: "cowswap_transactions.csv"
    block_tracker: "{protocol}_block_tracker.csv"
    consolidated: "consolidated_transactions.csv"

# Listener Configuration
listeners:
  # Common settings for all listeners
  common:
    max_blocks_per_scan: 1000
    retry_attempts: 3
    retry_delay: 1.0
    rate_limit_delay: 0.5
    
  # Protocol-specific settings
  relay:
    chunk_size: 100
    delay: 0.5
    max_blocks: 1000
    
  portals:
    chunk_size: 100
    delay: 0.5
    max_blocks: 1000
    
  thorchain:
    api_rate_limit: 1.0  # seconds between API calls
    max_swaps_per_request: 100
    
  cowswap:
    chunk_size: 100
    delay: 0.5
    max_blocks: 1000

# Volume Thresholds
thresholds:
  minimum_volume_usd: 13.0
  minimum_affiliate_fee_usd: 0.01
  
# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/shapeshift_tracker.log"
  
# Monitoring and Alerts
monitoring:
  health_check_interval: 300  # 5 minutes
  alert_on_failure: true
  max_consecutive_failures: 3
